name: Compress Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  compress:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install 7-Zip
      run: choco install 7zip --yes

    - name: Run compression script
      run: ./compress_file.ps1 -inputFile "D:\a\7z_compress\7z_compress\test.file" -outputFile "D:\a\7z_compress\7z_compress\test.file.7z" -logFile "D:\a\7z_compress\7z_compress\compression.log"
      shell: pwsh
